# Generated by Django 3.2 on 2023-01-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=254)),
                ('goal_description', models.TextField()),
                ('goal_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
