# Generated by Django 3.2 on 2023-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='book_title',
            field=models.CharField(max_length=200),
        ),
    ]
